from pdg.models import ReportDef, SectionDef

_LOADING_LEVELS = [
    "10%",
    "20%",
    "30%",
    "40%",
    "50%",
    "60%",
    "70%",
    "80%",
    "90%",
    "100%",
]

POWER_QUALITY_REPORT = ReportDef(
    key="power_quality",
    name="Power Quality Study (PP-600-PQ-001)",
    sections=[
        SectionDef(
            key="5.6",
            title="5.6 – Harmonic Spectrum of Inverter (10%–100%)",
            description="10 CSVs for loading levels 10% to 100%. Cols: Harmonic_Order, Ia_pu, Ib_pu, Ic_pu",
            heading_prefix="Harmonic Spectrum at",
            loading_levels=_LOADING_LEVELS,
            graph_type="bar",
            graph_xlabel="Harmonic Order",
            graph_ylabel="Current (p.u.)",
        ),
        SectionDef(
            key="7_current",
            title="7 – Harmonic Analysis: Current Harmonics (10%–100%)",
            description="10 CSVs for loading levels 10% to 100%. Cols: Harmonic_Order, Phase_R, Phase_Y, Phase_B, IEEE_Limit_pct, Limit_Passed",
            heading_prefix="Individual Current Harmonic Distortion at",
            loading_levels=_LOADING_LEVELS,
            graph_type="bar",
            graph_xlabel="Harmonic Order",
            graph_ylabel="Current Harmonic (%)",
            ieee_limits={
                "2": 1.0,
                "3": 2.0,
                "4": 1.0,
                "5": 2.0,
                "6": 1.0,
                "7": 2.0,
                "8": 2.0,
                "9": 2.0,
                "10": 2.0,
                "11": 1.0,
                "12": 1.0,
                "13": 1.0,
                "14": 1.0,
                "15": 1.0,
                "16": 1.0,
                "17": 0.75,
                "18": 0.75,
                "19": 0.75,
                "20": 0.75,
                "21": 0.75,
                "22": 0.75,
                "23": 0.3,
                "24": 0.3,
                "25": 0.3,
                "26": 0.3,
                "27": 0.3,
                "28": 0.3,
                "29": 0.3,
                "30": 0.3,
                "31": 0.3,
                "32": 0.3,
                "33": 0.3,
                "34": 0.3,
                "35": 0.15,
                "36": 0.15,
                "37": 0.15,
                "38": 0.15,
                "39": 0.15,
                "40": 0.15,
                "41": 0.15,
                "42": 0.15,
                "43": 0.15,
                "44": 0.15,
                "45": 0.15,
                "46": 0.15,
                "47": 0.15,
                "48": 0.15,
                "49": 0.15,
                "50": 0.15,
                "TDD": 1.5,
            },
        ),
        SectionDef(
            key="7_voltage",
            title="7 – Harmonic Analysis: Voltage Harmonics (10%–100%)",
            description="10 CSVs for loading levels 10% to 100%. Cols: Harmonic_Order, Phase_R, Phase_Y, Phase_B, IEEE_Limit_pct, Limit_Passed",
            heading_prefix="Individual Voltage Harmonic Distortion at",
            loading_levels=_LOADING_LEVELS,
            graph_type="bar",
            graph_xlabel="Harmonic Order",
            graph_ylabel="Voltage Harmonic (%)",
            ieee_limits={str(h): 1.0 for h in range(2, 51)} | {"THD": 1.5},
        ),
        SectionDef(
            key="7_verification",
            title="7 – Harmonic Analysis: Model Verification (10%–100%)",
            description="10 CSVs for loading levels 10% to 100%. Cols: Harmonic_Order, Inverter_R, Inverter_Y, Inverter_B, Model_R, Model_Y, Model_B",
            heading_prefix="Inverter Data vs PSCAD Model at",
            loading_levels=_LOADING_LEVELS,
        ),
        SectionDef(
            key="9",
            title="9 – DC Injection",
            description="1 CSV with FFT data. Cols: Time, IPOIDCA, IPOIDCB, IPOIDCC",
            heading_prefix="DC Injection Analysis",
            graph_type="line",
            graph_xlabel="Time",
            graph_ylabel="DC Current (A)",
        ),
        SectionDef(
            key="10",
            title="10 – Flicker Analysis",
            description="1 CSV with flicker data. Cols: CPF_Percent, Class",
            heading_prefix="Flicker Analysis",
            graph_type="line",
            graph_xlabel="CPF (%)",
            graph_ylabel="Class",
        ),
        SectionDef(
            key="annexure_b",
            title="Annexure B – Cable Schedule",
            description="1 CSV. Cols: Sr_No, From, To, CAD_Length, Additional_Length, Total_Length",
            heading_prefix="Cable Schedule",
        ),
    ],
)
